name: Build and Push Docker Image

on:
  push:
    branches: [ main ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Docker image
        run: |
          docker build -t "$GITHUB_USERNAME/$IMAGE_NAME:$TAG" .

      - name: Log in to GitHub Container Registry
        run: docker login ghcr.io -u "$GITHUB_USERNAME" -p "${{ secrets.GITHUB_TOKEN }}"

      - name: Push Docker image
        env:
          IMAGE_NAME: "$IMAGE_NAME"
          TAG: tag1
        run: |
          docker tag "$GITHUB_USERNAME/$IMAGE_NAME:$TAG" "ghcr.io/$GITHUB_USERNAME/$IMAGE_NAME:$TAG"
          docker push "ghcr.io/$GITHUB_USERNAME/$IMAGE_NAME:$TAG"
          if [ $? -eq 0 ]; then
            echo "Pomyślnie wypchnięto obraz: ghcr.io/$GITHUB_USERNAME/$IMAGE_NAME:$TAG"
          else
            echo "Błąd podczas wypychania obrazu"
          fi